name: goreleaser

on:
  push:
    tags:
      - '*'
    branches:
      - 'develop'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
      - uses: goreleaser/goreleaser-action@v4
        if: ${{ github.ref_type == 'tag' }}
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v4
        if: ${{ github.ref_type == 'branch' }}
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        if: ${{ github.ref_type == 'branch' }}
        with:
          name: ofdl
          path: dist/*
